name: Translation To GitHub
on:
  issues:
    types: [opened]
  schedule:
    - cron: "0 */2 * * *"
jobs:
  check-issue:
    if: contains(github.event.issue.labels.*.name, '自动化:paratranz→Github') && github.event_name != 'schedule'
    name: Check Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Issue Check
        run: |
          echo "检测成功：${{ github.event.issue.labels.*.name }}"
  Translation-To-GitHub:
    name: Translation To GitHub
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, '自动化:paratranz→Github') || github.event_name == 'schedule'
    environment: PARATRANZ_ENV
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
      FILE_PATH: ./
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_ID: ${{ vars.ID }}
      GIT_PATH: ${{ vars.G_PATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install requests
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "VM[BOT]"
          git config --global pull.rebase false
      - name: Initialize and Checkout Branch
        run: |
          git init
          git fetch origin
          git branch develop
          git push -u origin develop
          git checkout develop
          git reset --hard main
      - name: Paratranz To zh_cn
        run: |
          python .github/workflows/translation2github.py
      - name: Upload To develop
        run: |
          git add .
          if [[ -n $(git status -s) ]]; then
            echo '译文更改'
            git commit -m 'paratranz上传'
            git pull origin develop --allow-unrelated-histories
            git push origin develop
            gh pr create --title 'paratranz上传' --body '自动PR'
            sleep 1
            gh pr merge develop --merge
            git checkout main
            git branch -D develop
            git push origin --delete develop
          else
            echo '译文未更改'
            git checkout main
            git branch -D develop
            git push origin --delete develop
          fi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CNPack
          path: ${{ github.workspace }}/CNPack

  close-issue:
    name: Close Issue
    needs: check-issue
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
